name: 'GraalVM Downloader Tests'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [graalvm-ce-java11-22.1.0, graalvm-ee-java17-22.1.0]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Check 'get' and 'ee-token' scripts
        run: shellcheck get ee-token
        if: matrix.os == 'ubuntu-latest'
      - name: Run 'get' script
        run: |
          python3 -m http.server 8080 &
          sleep 5
          bash <(curl -sL http://localhost:8080/get) -h
          bash <(curl -sL http://localhost:8080/get) -c native-image ${{ matrix.version }}
          bash <(curl -sL http://localhost:8080/get) -l
        env:
          GRAAL_EE_DOWNLOAD_TOKEN: ${{ secrets.GRAAL_EE_DOWNLOAD_TOKEN }}
      - name: Check environment
        run: |
          path_suffix="" && [[ "$(uname -s)" != "Darwin" ]] || path_suffix="/Contents/Home"
          export GRAALVM_HOME="$HOME/.graalvm/${{ matrix.version }}${path_suffix}"
          export PATH="$HOME/.graalvm/${{ matrix.version }}${path_suffix}/bin:$PATH"
          export JAVA_HOME="$HOME/.graalvm/${{ matrix.version }}${path_suffix}"
          $GRAALVM_HOME/bin/gu --version
          native-image --version
          java --version
      - name: Re-run 'get' script
        run: ./get ${{ matrix.version }}
