name: 'GraalVM Downloader Tests'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [graalvm-ce-java11-22.1.0, graalvm-ee-java17-22.1.0]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Check 'core' and 'ee-token' scripts
        run: shellcheck core ee-token
        if: matrix.os == 'ubuntu-latest'
      - name: Run 'core' script
        run: |
          python3 -m http.server 8080 &
          sleep 5
          bash <(curl -sL http://localhost:8080/core) -h
          bash <(curl -sL http://localhost:8080/core) -c native-image,espresso --to $HOME ${{ matrix.version }}
          bash <(curl -sL http://localhost:8080/core) -c native-image,espresso --to $HOME ${{ matrix.version }}
        env:
          GRAAL_EE_DOWNLOAD_TOKEN: ${{ secrets.GRAAL_EE_DOWNLOAD_TOKEN }}
      - name: Check environment
        run: |
          path_suffix="" && [[ "$(uname -s)" != "Darwin" ]] || path_suffix="/Contents/Home"
          export GRAALVM_HOME="$HOME/${{ matrix.version }}${path_suffix}"
          export PATH="$HOME/${{ matrix.version }}${path_suffix}/bin:$PATH"
          export JAVA_HOME="$HOME/${{ matrix.version }}${path_suffix}"
          $GRAALVM_HOME/bin/gu --version
          native-image --version
          java --version
      - name: Ensure 'core' script fails
        run: |
          set -x
          exit_code=0 && ./core foo || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core ${{ matrix.version }} -c "native-image nodejs" || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core ${{ matrix.version }} --to /invalid/path || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core graalvm- || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core graalvm-ce || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core graalvm-ce-java8-22.1.0 || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core graalvm-ce-java11 || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core graalvm-ce-java11-0.0.0 || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          exit_code=0 && ./core graalvm-ee-java11-0.0.0 || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
          export GRAAL_EE_DOWNLOAD_TOKEN="invalid"
          exit_code=0 && ./core graalvm-ee-java11-22.1.0 || exit_code=$?
          [[ ${exit_code} -ne 0 ]] || { echo "Previous line did not fail"; false; }
